### ISSUE TITLE
Bundler does not support nested CSS

### ISSUE THREAD

**Issue by portfolioris** [Shazwazza/Smidge#209]
I assume Smidge is responsible for bundling CSS when adding a CSS file to a package.

If I use this css:

```css
.some-class {
    & .some-sub-class {
        color: lime;
    }
}
```

The bundled output to `/sb/umbraco-backoffice-css.css.v638545637345803210` returns a 500 error.

My guess I doesn't support the relatively new syntax.
